### ISSUE TITLE
Rank the criteria for matching

### ISSUE THREAD

**Issue by sean-meade** [sean-meade/Wookiee-Woo#3]
There are different things someone can match on. This task is to list and rank those criteria in order of importance so we know what order to focus on them.

**Comment by smtilson** [comment]
Should I add my suggestions for this in a comment here? Or add a document to the repo with the information in it?

**Comment by smtilson** [comment]
I think I misunderstood this. I thought the question was in what order should we be adding things to match on to the project.

Determining the weights for each matching criteria is a more interesting question that I have been thinking about. There are a couple of different stages of development we could do for this.

**Comment by smtilson** [comment]
Needs to be added to word doc.

**Comment by smtilson** [comment]
I have added the ordering to the word doc. I am open to reordering, but I think this is good for a first iteration.
